Fix/operator fixes
Vizzuality/otp-portal pull request #126
Opened 2021-01-22 10:03 UTC by blayhem

- [X] Resets FMU filter on operator page load ([174210621](https://www.pivotaltracker.com/story/show/174210621))
- [X] Changes the length of the % bars next to the pie chart ([174210432](https://www.pivotaltracker.com/story/show/174210432))

TODO: need to check any possible mismatch in the bars with the non-required-docs-count-as-valid feature...

2021-01-25 12:54 UTC, mbarrenechea requested changes

2021-01-25 12:54 UTC, mbarrenechea commented on components/operators-detail/documentation.js
> +import sortBy from 'lodash/sortBy';
imported but not used

2021-01-25 13:23 UTC, blayhem commented on components/operators-detail/documentation.js
> +import sortBy from 'lodash/sortBy';
nice catch, thanks!

2021-03-03 08:32 UTC, mbarrenechea approved these changes

2021-03-03 08:32 UTC, merged